### ISSUE TITLE
HKSV & 2 way audio

### ISSUE THREAD

**Issue by adalarce** [brownad/homebridge-doorbird#624]
This plug in makes a Doorbird worth having, thank you so much. Just wanted to hop in and say HomeKit Secure Video and 2way audio support is the missing link and would be the ultimate update, any chance of implementation?

**Comment by hjdhjd** [comment]
High...at some point. I'll be expanding capabilities over the next year to provide consistency across all the plugins I support. Thanks.

**Comment by adalarce** [comment]
Let me know if I can sponsor its implementation, it would be game changer. Specially from you, always flawless plug ins!
