### ISSUE TITLE
Two way audio and responsiveness

### ISSUE THREAD

**Issue by spaceg00se-r** [brownad/homebridge-doorbird#626]
I started using your plugin a few days ago and I must say... wow! Really nice to see my doorbird in Homekit! However, two little things are bothering me:

1. Currently speaking back to the doorbird station is not possible. I've seen comments in the project like "Add support for twoway audio and linting" which triggered hope in me. Is there anything on the horizon regarding two way audio?
2. Video stream start speed: it somehow takes quite long for the video stream to start off when openend in homekit (i'm running homebridge on a PI 4). Is there anything that can be done to speed this up? Maybe even a workaround like lowering the quality somehow? I have played around with scrypted and there the stream starts almost instantly - however, with scrypted the entire interation as a "doorbell" and the usage of relais is completely missing.

Thanks for your help and keep up the great work!

**Comment by hjdhjd** [comment]
Your welcome! 

There will be support forthcoming when I get to it...real life and my other extracurricular projects take precedence.

More to come in the future. Cheers.
