### ISSUE TITLE
Event monitoring (motion, ring): new Version 2, Version 1 will be removed

### ISSUE THREAD

**Issue by mrhund** [brownad/homebridge-doorbird#637]
When scrolling through the settings I saw that there is a new option for the notifications (motion, ring), which is called "local notifcations". You can select "Version2-only (for better performace)" or "Version2 and Version1".

So I looked into the API description (https://www.doorbird.com/downloads/api_lan.pdf?rev=0.36) it says:
"Since November 2023 there is a new “v.2” handling for encrypting/decrypting the events. The version 1 has been deprecated and will be removed in the future."

As the last changes in this project have been made 3 years ago, I am sure this is not considered in the project and a break of functionaliy can happen in the future.

**Comment by hjdhjd** [comment]
Yep…I’ll be looking at this more later in the year and releasing an updated version complete with some long-requested features. Appreciate you raising it. Stay tuned!

**Comment by mrhund** [comment]
In this case it is far away from "closed", why closing the issue?

**Comment by hjdhjd** [comment]
Because that’s how I choose to manage my projects, please respect it. The issue’s on my radar. Thanks.
