### ISSUE TITLE
Homebridge 2.0

### ISSUE THREAD

**Issue by spaceg00se-r** [brownad/homebridge-doorbird#638]
Hi

Do you know if your plugin will be Homebridge 2.0 compatible? If so, do you plan to make the necessary changes to **package.json** (https://github.com/homebridge/homebridge/wiki/Updating-To-Homebridge-v2.0)? If not, do you plan to make the necessary changes? Would be really great if this plugin would still work with 2.0 and beyond. Thanks a lot!

**Comment by hjdhjd** [comment]
Since I’m one of the Homebridge authors and maintainers…yes, it will. :smile: The package.json doesn’t need updating at all…it’s merely a minor cosmetic issue.

**Comment by spaceg00se-r** [comment]
Nice. Thanks! 
With "it will" do you mean that it already is compatible in the current state or that you will have to make updates to the plugin when HB 2.0 launches?

**Comment by spaceg00se-r** [comment]
Hey @hjdhjd. Sorry for bugging you again with this topic. However, my last question here was not fully answered. Is this plugin already working with 2.0 without any problems? Will you make any updates in the future?

**Comment by hjdhjd** [comment]
Once we release Homebridge 2.0 (meaning it’s production, not beta), this plugin will work with it. This plugin will remain actively maintained. I have nothing further to say at this time.
